solution.exe Dataset\0\input0.raw Dataset\0\input1.raw Dataset\0\output.raw
solution.exe Dataset\1\input0.raw Dataset\1\input1.raw Dataset\1\output.raw
solution.exe Dataset\2\input0.raw Dataset\2\input1.raw Dataset\2\output.raw
solution.exe Dataset\3\input0.raw Dataset\3\input1.raw Dataset\3\output.raw
solution.exe Dataset\4\input0.raw Dataset\4\input1.raw Dataset\4\output.raw
solution.exe Dataset\5\input0.raw Dataset\5\input1.raw Dataset\5\output.raw
solution.exe Dataset\6\input0.raw Dataset\6\input1.raw Dataset\6\output.raw
solution.exe Dataset\7\input0.raw Dataset\7\input1.raw Dataset\7\output.raw
solution.exe Dataset\8\input0.raw Dataset\8\input1.raw Dataset\8\output.raw
solution.exe Dataset\9\input0.raw Dataset\9\input1.raw Dataset\9\output.raw